version: '3.6'

services:

  appjudge:
    container_name: appjudge
    build:
      context: ./services/appjudgeAPI
      dockerfile: Dockerfile
    volumes:
      - './services/appjudgeAPI:/usr/src/app'
    ports:
      - 5001:5000
    expose:
      - '5000'
    environment:
      - FLASK_ENV=developement
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@appjudge-db:5432/appjudge
    depends_on:
      - appjudge-db

  appjudge-db:
    container_name: appjudge-db
    build:
      context: ./services/appjudgeAPI/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  nginx:
    container_name: appjudge-nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - appjudge
      - react-client-admin


  react-client-admin:
    container_name: react-client-admin
    build:
      context: ./services/react-client-admin
      dockerfile: Dockerfile
    volumes:
      - './services/react-client-admin:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    expose:
      - '3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_APPJUDGE_SERVICE_URL=${REACT_APP_APPJUDGE_SERVICE_URL}
    depends_on:
      - appjudge